# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-40-90-w0.3-cl-test --aug_data_weight 0.3 --model_name_or_path=gpt2 --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 40 --confidence_threshold_r 90 --add_contrastive_loss

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-40-100-w0.2-cl --aug_data_weight 0.2 --model_name_or_path=gpt2 --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 40 --confidence_threshold_r 100 --add_contrastive_loss

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-50-90-w0.2-cl --aug_data_weight 0.2 --model_name_or_path=gpt2 --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 50 --confidence_threshold_r 90 --add_contrastive_loss

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-50-90-w0.3-b4-aug-cl --aug_data_weight 0.3 --model_name_or_path=gpt2 --per_gpu_train_batch_size=8 --save_steps=-1 --cross_validate --confidence_threshold_s 50 --confidence_threshold_r 90 --add_contrastive_loss

#python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-0-0-w0.3-b4-aug-cl-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2 --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 50 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot --num_train_epochs 2

#python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-40-80-w0.3-b4-aug-cl-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2 --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 40 --confidence_threshold_r 80 --add_contrastive_loss --zero_shot 

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-50-90-w0.3-b4-aug-cl-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2 --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 50 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot --num_train_epochs 2

#python cqr/pipeline.py --train_gold_file data/eval_topics_canard.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-90-110-w0.3-b4-cl-canard --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 90 --confidence_threshold_r 110 --add_contrastive_loss 

#python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/sample2_s.jsonl --train_unlabeled_file_r data/unlabeled_data/sample2_r.jsonl --output_dir pipeline_models/sample2-few-shot --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=8 --save_steps=-1 --cross_validate --confidence_threshold_s 90 --confidence_threshold_r 110 --add_contrastive_loss 

#python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0.3-b4-aug-cl-zero-shot-0.03 --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot --contrastive_weight 0.03

#python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/sample2_s.jsonl --train_unlabeled_file_r data/unlabeled_data/sample2_r.jsonl --output_dir pipeline_models/sample2-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=8 --save_steps=-1 --zero_shot --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss 

python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/sample4_s.jsonl --train_unlabeled_file_r data/unlabeled_data/sample4_r.jsonl --output_dir pipeline_models/sample4-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=8 --save_steps=-1 --zero_shot --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss 
