# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-50-80-w0.5 --aug_data_weight 0.5 --model_name_or_path=gpt2 --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 50 --confidence_threshold_r 80 

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-50-90-w0.5 --aug_data_weight 0.5 --model_name_or_path=gpt2 --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 50 --confidence_threshold_r 90 

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-30-90-w0.5 --aug_data_weight 0.5 --model_name_or_path=gpt2 --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 50 --confidence_threshold_r 100 

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-50-90-w0.3-b8-cl --aug_data_weight 0.3 --model_name_or_path=gpt2 --per_gpu_train_batch_size=8 --save_steps=-1 --cross_validate --confidence_threshold_s 50 --confidence_threshold_r 90 --add_contrastive_loss

#python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-90-110-w0.3-b4-cl --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 90 --confidence_threshold_r 110 --add_contrastive_loss

#python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-0-0-w0.3-b2 --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=2 --save_steps=-1 --cross_validate --confidence_threshold_s 0 --confidence_threshold_r 0 --add_contrastive_loss

#python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-60-90-w0.3-b4-aug-cl-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2 --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 60 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot

#python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-50-70-w0.3-b4-aug-cl-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --cross_validate --confidence_threshold_s 50 --confidence_threshold_r 70 --add_contrastive_loss --zero_shot

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0.3-b4-aug-cl-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-90-110-w0.3-b4-aug-cl-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 90 --confidence_threshold_r 110 --add_contrastive_loss --zero_shot 

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-70-90-w0.3-b4-aug-cl-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2 --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot 

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-80-100-w0.3-b4-aug-cl-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 80 --confidence_threshold_r 100 --add_contrastive_loss --zero_shot

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-80-100-w0.3-b4-aug-cl-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 80 --confidence_threshold_r 100 --add_contrastive_loss --zero_shot

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-80-100-w0.3-b4-aug-cl-zero-shot --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 80 --confidence_threshold_r 100 --add_contrastive_loss --zero_shot

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0-b4-aug-cl-zero-shot --aug_data_weight 0 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0.1-b4-aug-cl-zero-shot --aug_data_weight 0.1 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0.2-b4-aug-cl-zero-shot --aug_data_weight 0.2 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0.4-b4-aug-cl-zero-shot --aug_data_weight 0.4 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0.3-b4-aug-cl-zero-shot-0.01 --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot --contrastive_weight 0.01

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0.3-b4-aug-cl-zero-shot-0.02 --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot --contrastive_weight 0.02

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0.3-b4-aug-cl-zero-shot-0.03 --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot --contrastive_weight 0.03

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0.3-b4-aug-cl-zero-shot-0.04 --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot --contrastive_weight 0.04

# python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0.3-b4-aug-cl-zero-shot-0.05 --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot --contrastive_weight 0.05

python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/pipeline-gpt2-medium-70-90-w0.3-b4-aug-cl-zero-shot-0 --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 70 --confidence_threshold_r 90 --add_contrastive_loss --zero_shot --contrastive_weight 0

python cqr/pipeline.py --train_gold_file data/eval_topics.jsonl --train_unlabeled_file_s data/unlabeled_data/unlabeled_self_learn.jsonl --train_unlabeled_file_r data/unlabeled_data/unlabeled_canard.jsonl --output_dir pipeline_models/trec --aug_data_weight 0.3 --model_name_or_path=gpt2-medium --per_gpu_train_batch_size=4 --save_steps=-1 --confidence_threshold_s 90 --confidence_threshold_r 110 --add_contrastive_loss 